### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by dzheltkov** [AliRN9/cals_polynom#1]
1) `std::vector` и `Poly` стоит передавать в функции по константной ссылке, а не копируя.
2) Нужен парсер.
3) Собирать проект я пока не пробовал, подожду более финальной версии.

**Comment by AliRN9** [comment]
Задание вроде сделано

**Comment by dzheltkov** [comment]
Задание зачтено.

Единственное, забыли в `std::ostream &operator<<(std::ostream &os, Poly p)` написать `return os;` в конце а также передать полином по константной ссылке.
